@startuml
class VoiceController {
    + StartSpeaking(message:string) : void
    + StopSpeaking() : void
    + StartListening() : void
    + StopListening() : void
}
MonoBehaviour <|-- VoiceController
VoiceController --> "Instance" VoiceController
VoiceController --> "input_text" TMP_Text
VoiceController --> "recordingIcon" GameObject
@enduml
